# Write your code below this line ??
print("Day 1 - Python Print function")
print("The function is decalred like this:")
print("print('what to print')")
print(" ")
print(" Hello world \n Hello world \n Hello world")
print("\n")
print("Hello " + input("What is your name please?"))
print("\n")
print( len( input("What is your name? ")))
name = input(" What is your name? ")
print(name)
print( len(name))
